### PR TITLE
(New module) Touch

### PR DESCRIPTION
**Pull request by jsbrittain**
Provide a generic 'touch' module, which acts to trigger other modules/actions.

Snakemake is a file-based system where the create of new files to act as triggers is common. This module add this facility.

### CODE REVIEW

**Comment by rowannicholls** [comment]
Hi @jsbrittain I'm wondering why the `output_namespace` variable in the `config.yaml` file is `out` yet the file that is created is inside a directory called `utility_touch`? In the Snakefile it seems as if the directory name should be taken from this variable?

**Comment by jsbrittain** [comment]
> Hi @jsbrittain I'm wondering why the `output_namespace` variable in the `config.yaml` file is `out` yet the file that is created is inside a directory called `utility_touch`? In the Snakefile it seems as if the directory name should be taken from this variable?

@rowannicholls Yes, that's correct. But the `output_namespace` variable is overwritten when we build the module into a workflow using GRAPEVNE (check out the `config/config.yaml` file that is generated when you do this). This is the primary mechanism that we use to chain modules together. At the moment the output namespace will be overwritten with the name of the module (largely for ease of navigation during development). The default value (`out`) is there for testing purposes (i.e. when running snakemake directly on the module, without routing through GRAPEVNE).

**Comment by rowannicholls** [comment]
I see, thanks

**Review by rowannicholls — COMMENTED** [review]
Working as expected

**Pull request merged**
